// <auto-generated />
using GeniyIdiotWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeniyIdiotWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316141610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("GeniyIdiotWebApi.Models.AnswerAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserAnswer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AnswerAttempts");
                });

            modelBuilder.Entity("GeniyIdiotWebApi.Models.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("GeniyIdiotWebApi.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Answer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = 6,
                            Title = "Сколько будет два плюс два умноженное на два?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = 9,
                            Title = "Бревно нужно распилить на 10 частей. Сколько распилов нужно сделать?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = 25,
                            Title = "На двух руках 10 пальцев. Сколько пальцев на 5 руках?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = 60,
                            Title = "Укол делают каждые полчаса. Сколько нужно минут, чтобы сделать три укола?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = 2,
                            Title = "Пять свечей горело, две потухли. Сколько свечей осталось?"
                        });
                });

            modelBuilder.Entity("GeniyIdiotWebApi.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Идиот"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кретин"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Дурак"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Нормальный"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Талант"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Гений"
                        });
                });

            modelBuilder.Entity("GeniyIdiotWebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
